name: dart_dot_reporter
description: Dot test reporter for Dart & Flutter & Human. Makes test results clear from the high-level view.
version: 1.0.3
homepage: https://github.com/apastuhov/dart_dot_reporter
repository: https://github.com/apastuhov/dart_dot_reporter
publish_to: none

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

executables:
  dart_dot_reporter: dart_dot_reporter

dependencies:
  analyzer_rules:
    path: ../analyzer_rules

dev_dependencies:
  mocktail: 0.1.4
  pedantic: 1.11.1
  test: 1.17.10
