include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - README.md
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
  enable-experiment:
    - extension-methods

linter:
  rules:
    annotate_overrides: true
    constant_identifier_names: true
    omit_local_variable_types: false # ignore dart warning https://github.com/dart-lang/pedantic/issues/45
    prefer_single_quotes: true
    prefer_final_fields: true
    unnecessary_this: true
    dead_code: true
    always_declare_return_types: true
    prefer_final_locals: true
    unnecessary_lambdas: true
    unnecessary_await_in_return: true
    unnecessary_parenthesis: true
    sort_child_properties_last: true
    prefer_if_null_operators: true
    prefer_const_declarations: true
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    always_put_required_named_parameters_first: true
    always_require_non_null_named_parameters: true
    always_specify_types: false
    avoid_empty_else: true
    avoid_as: true
    avoid_init_to_null: true
    avoid_return_types_on_setters: true
    await_only_futures: true
    camel_case_types: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    control_flow_in_finally: true
    empty_constructor_bodies: true
    empty_statements: true
    hash_and_equals: true
    implementation_imports: true
    invariant_booleans: true
    iterable_contains_unrelated_type: true
    library_names: true
    library_prefixes: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    non_constant_identifier_names: true
    one_member_abstracts: false
    only_throw_errors: true
    overridden_fields: true
    package_api_docs: true
    package_names: true
    package_prefixed_library_names: true
    prefer_is_not_empty: true
    prefer_mixin: true
    public_member_api_docs: false
    slash_for_doc_comments: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    valid_regexps: true

