
workflows:
  test-flow:
    name: Test
    max_build_duration: 20
    environment:
      flutter: 2.6.0-11.0.pre
      xcode: latest
      cocoapods: default
      groups:
        - coverall
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      tag_patterns:
        - pattern: '*'
          include: true
      cancel_previous_builds: true
    scripts:
      - name: Flutter pub get
        script: |
          CWD=`pwd`
          PACKAGES_RELATIVE_PATH="packages"
          PACKAGES_DIR="$CWD/$PACKAGES_RELATIVE_PATH"
          flutter pub get
          for d in $(ls $PACKAGES_DIR); do
              PACKAGE_DIR="$PACKAGES_DIR/$d"
              echo "Entering $PACKAGES_RELATIVE_PATH/$d"
              cd $PACKAGE_DIR && flutter pub get
          done
      - name: Static analysis - lib
        script: |
          flutter analyze --fatal-warnings
      - name: Dart Code Metrics - lib
        script: |
          flutter pub global activate dart_code_metrics
          mkdir -p metrics-results
          flutter pub global run dart_code_metrics:metrics analyze lib --reporter=json > metrics-results/dart_code_metrics.json      
        test_report: metrics-results/dart_code_metrics.json
      - name: Dart Code Metrics - packages/rijks_api
        script: |
          cd packages/rijks_api
          flutter pub global activate dart_code_metrics
          mkdir -p metrics-results
          flutter pub global run dart_code_metrics:metrics analyze lib --reporter=json > metrics-results/dart_code_metrics.json      
        test_report: packages/rijks_api/metrics-results/dart_code_metrics.json
      - name: Dart Code Metrics - packages/test_app_blocs
        script: |
          cd packages/test_app_blocs
          flutter pub global activate dart_code_metrics
          mkdir -p metrics-results
          flutter pub global run dart_code_metrics:metrics analyze lib --reporter=json > metrics-results/dart_code_metrics.json      
        test_report: packages/test_app_blocs/metrics-results/dart_code_metrics.json
      - name: Dart Code Metrics - packages/test_app_domain
        script: |
          cd packages/test_app_domain
          flutter pub global activate dart_code_metrics
          mkdir -p metrics-results
          flutter pub global run dart_code_metrics:metrics analyze lib --reporter=json > metrics-results/dart_code_metrics.json      
        test_report: packages/test_app_domain/metrics-results/dart_code_metrics.json
      - name: Dart Code Metrics - packages/test_app_shared
        script: |
          cd packages/test_app_shared
          flutter pub global activate dart_code_metrics
          mkdir -p metrics-results
          flutter pub global run dart_code_metrics:metrics analyze lib --reporter=json > metrics-results/dart_code_metrics.json      
        test_report: packages/test_app_shared/metrics-results/dart_code_metrics.json
      - name: Dart Code Metrics - packages/test_app_ui_kit
        script: |
          cd packages/test_app_ui_kit
          flutter pub global activate dart_code_metrics
          mkdir -p metrics-results
          flutter pub global run dart_code_metrics:metrics analyze lib --reporter=json > metrics-results/dart_code_metrics.json      
        test_report: packages/test_app_ui_kit/metrics-results/dart_code_metrics.json
      - name: Unit tests + Generate coverage file
        script: |
          ./scripts/coverage.sh
      - name: Coverage badge
        script: |
          set -e
          echo "repo_token: $COVERALLS_TOKEN" > .coveralls.yml
          gem install coveralls-lcov
          coveralls-lcov coverage/lcov.info
    artifacts:
      - flutter_drive.log
    publishing:
      slack:
        channel: '#ci'
        notify_on_build_start: false