name: flutter_test_app
description: Flutter test app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  analyzer_rules:
    path: packages/analyzer_rules
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_simple_dependency_injection: ^2.0.0
  photo_view: ^0.13.0
  rijks_api:
    path: packages/rijks_api
  test_app_domain:
    path: packages/test_app_domain
  test_app_ui_kit:
    path: packages/test_app_ui_kit

dev_dependencies:
  dart_dot_reporter:
    path: packages/dart_dot_reporter
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
