name: test_app_ui_kit
description: Common UI Kit components
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  analyzer_rules:
    path: ../analyzer_rules
  flutter:
    sdk: flutter
  optimized_cached_image: ^3.0.0

dev_dependencies:
  dart_dot_reporter:
    path: ../dart_dot_reporter
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.11.0
  test: ^1.17.12

# for material Icons
flutter:
  uses-material-design: true

  fonts:
    - family: .SF UI Display
      fonts:
        - asset: assets/fonts/SFUIDisplay-Semibold.otf
    - family: .SF UI Text
      fonts:
        - asset: assets/fonts/SFUIText-Regular.ttf
  