name: test_app_domain
description: Manages domain layer
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  analyzer_rules:
    path: ../analyzer_rules
  equatable: ^2.0.3

dev_dependencies:
  build_runner: ^2.1.4
  coverage: ^1.0.3
  dart_dot_reporter:
    path: ../dart_dot_reporter
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4
  rijks_api:
    path: ../rijks_api
  test: ^1.17.12