name: test_app_shared
description: Shared utils, extensions, service locator
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  analyzer_rules:
    path: ../analyzer_rules
  flutter:
    sdk: flutter
  flutter_simple_dependency_injection: ^2.0.0
  get_it: ^7.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter