name: rijks_api
description: A Dart API Client for the Rijks Museum API.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  analyzer_rules:
    path: ../analyzer_rules
  flutter:
    sdk: flutter
  http: ^0.13.3
  json_annotation: ^4.0.1
  test_app_domain:
    path: ../test_app_domain

dev_dependencies:
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0
  json_serializable: ^5.0.0